# Generated by Django 3.2 on 2021-05-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='typ_vozidla',
            new_name='znacka_typ_vozidla',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='znacka',
        ),
    ]
