# Generated by Django 3.2 on 2021-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_zacatku_vypujcky', models.DateTimeField()),
                ('datum_konce_vypujcky', models.DateTimeField()),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
